export enum RegisterStatus {
  NEW = 'NEW',
  ADDRESS_DADATA = 'ADDRESS_DADATA',
  OPEN_ACCOUNT = 'OPEN_ACCOUNT',
  TWPG_SENDED = 'TWPG_SENDED',
  RETAILER_CREATED = 'RETAILER_CREATED',
  TERMINAL_CREATED = 'TERMINAL_CREATED',
  FILE_SENT = 'FILE_SENT',
  REG = 'REG',
  CLOSE = 'CLOSE',
}
